function MainFigure()

clear;
clc;

global vrep clientID jointHandle sensorDXHandle sensorSXHandle 
vrep = remApi('remoteApi');
vrep.simxFinish(-1);

IPaddress = '127.0.0.1';
port = 19997;
waitUntilConnected = true;
doNotReconnectOnceDisconnected = false;
timeOutInMs = 5000;
waitToReTry = 5;

clientID = vrep.simxStart(IPaddress, port, waitUntilConnected, doNotReconnectOnceDisconnected, timeOutInMs, waitToReTry);

vrep.simxStartSimulation(clientID, vrep.simx_opmode_oneshot);

[~, jointHandle] = vrep.simxGetObjectHandle(clientID, 'Joint#', vrep.simx_opmode_oneshot_wait);

[~, sensorDXHandle] = vrep.simxGetObjectHandle(clientID, 'visionSensorDX#', vrep.simx_opmode_blocking);

[~, sensorSXHandle] = vrep.simxGetObjectHandle(clientID, 'visionSensorSX#', vrep.simx_opmode_blocking);

window = figure('Name', 'Command window', 'Color', 'cyan', 'Position', [50 50 900 600]);

nbText = uicontrol('Style', 'Text',...
                    'String', 'Per chiudere la simulazione spostati nella Cmd Window e premi un tasto',...
                    'Position', [50 560 500 15]);            

dxButton = uicontrol('Style', 'pushbutton',...
                        'String', 'Sposta la ripresa verso dx.',...
                        'FontName', 'Times New Roman',...
                        'FontWeight','bold',...
                        'Callback',@visionSensorDXMove,...
                        'Position', [10 70 210 40]);
                    
sxButton = uicontrol('Style', 'pushbutton',...
                        'String', 'Sposta la ripresa verso sx.',...
                        'FontName', 'Times New Roman',...
                        'FontWeight','bold',...
                        'Callback',@visionSensorSXMove,...
                        'Position', [230 70 210 40]);
                    
imageButton = uicontrol('Style', 'pushbutton',...
                        'String', 'Normal image pair.',...
                        'FontName', 'Times New Roman',...
                        'FontWeight','bold',...
                        'Callback',@imageScreen,...                        
                        'Position', [450 70 150 40]);                         
                    
falseColorButton = uicontrol('Style', 'pushbutton',...
                        'String', 'FalseColor difference.',...
                        'FontName', 'Times New Roman',...
                        'FontWeight','bold',...
                        'Callback',@falseColor,...                        
                        'Position', [10 10 200 40]);
                  
diffButton = uicontrol('Style', 'pushbutton',...
                        'String', 'Difference image.',...
                        'FontName', 'Times New Roman',...
                        'FontWeight','bold',...
                        'Callback',@diff,...                        
                        'Position', [220 10 150 40]);
                    
blendButton = uicontrol('Style', 'pushbutton',...
                        'String', 'Blend difference.',...
                        'FontName', 'Times New Roman',...
                        'FontWeight','bold',...
                        'Callback',@blendColor,...                        
                        'Position', [380 10 150 40]);  
                    
montageButton = uicontrol('Style', 'pushbutton',...
                        'String', 'Montage difference.',...
                        'FontName', 'Times New Roman',...
                        'FontWeight','bold',...
                        'Callback',@montageDiff,...                        
                        'Position', [540 10 170 40]);                         

imageScreen();


pause();
vrep.simxStopSimulation(clientID, vrep.simx_opmode_oneshot);
delete(window);

end